config/routes.rb
Rails.application.routes.draw do
  
  root to: 'pages#home'

  get "/login", to: "users#login", as: "login"
  post "/handle_login", to: 'users#handle_login'
  
  delete "/logout", to: "users#logout"

  get "/all_events", to: "events#all_events", as: "all_events"
  resources :event_categories, only: [:create]
  resources :events, only: [:index, :create, :show, :edit, :update, :destroy]
  resources :users, only: [:new, :create]
  resources :photos, only: [:index, :create, :destroy]


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :event_categories, dependent: :destroy
    has_many :events, through: :event_categories
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user, optional: true
  
  has_many :event_categories, dependent: :destroy
  has_many :categories, through: :event_categories
  has_many :photos, dependent: :destroy

  validates :title, presence: true
  

  def previous
    user.events.where(["date < ?", date]).order(:date).last
  end

  def next
    user.events.where(["date > ?", date]).order(:date).first
  end

  def days_until_or_since
    days = (self.date.to_datetime - DateTime.now).to_f.round
      if days.negative?
        "#{days.abs} day(s) since event"
      else 
        "#{days.abs} day(s) until event"
      end
  end

end

app/models/event_category.rb
class EventCategory < ApplicationRecord
  belongs_to :event
  belongs_to :category

  validates :category_id, uniqueness: {scope: :event_id, message: "is already taken"}
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :event
  validates :picture_url, presence: true
end

app/models/quote.rb
class Quote < ApplicationRecord
    
end

app/models/user.rb
class User < ApplicationRecord
    has_many :events, dependent: :destroy
    has_many :calendar_dates, through: :events

    validates :first_name, presence: true
    validates :last_name, presence: true
    validates :username, presence: true, uniqueness: true
    validates :password, presence: true, length: {minimum: 4, maximum: 11}, format: {without: /\s/}

    has_secure_password

    def selected_events
        events.select{|event| event.date > DateTime.now}
    end

    def upcoming_five_events
        selected_events.sort_by(&:date).take(5)
    end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :logged_in?

    before_action :authorized
    
    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end
    
    def logged_in?
        !!current_user
    end

    def authorized
        redirect_to login_path unless logged_in?
    end
        
    
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
end

app/controllers/event_categories_controller.rb
class EventCategoriesController < ApplicationController


    def create 
        category_ids = params[:event_category][:category_id]
            category_ids.each do |category_id|
                if category_id != "" 
                    event_category = EventCategory.create(category_id: category_id, event_id: flash[:event_id])
                        if event_category.valid? == false
                            flash[:category_errors] = event_category.errors.full_messages
                        end
                end
            end
        redirect_to event_path(flash[:event_id])
    end

    private

    def event_category_params 
        params.require(:event_category).permit(:event_id, :category_id)
    end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

    before_action :set_event, only: [:show, :destroy, :edit, :update]
    
    def index
        @event = Event.new
            if params[:event] && params[:event][:category_ids] 
                @events = @current_user.upcoming_five_events.select {|event| event.category_ids.include?(params[:event][:category_ids].to_i) }
            elsif params.has_key?(:select)
                @events = @current_user.events.select{|event| event.date.year == params[:select][:year].to_i && event.date.month == params[:select][:month].to_i}
            else
                @events = @current_user.upcoming_five_events
            end
        @event_errors = flash[:event_errors]
        @quote = Quote.all.sample.quote
    end

    def all_events
        @all_events = @current_user.events.sort_by(&:date)
    end

    def create
        event = @current_user.events.create(event_params)
        EventCategory.create(event_id: event.id, category_id: params[:event][:category_ids])
            if event.valid?
                redirect_to event_path(event)
            else
                flash[:event_errors] = event.errors.full_messages
                redirect_to events_path
            end
    end

    def show
        @event_category = EventCategory.new
        @categories = Category.all
        flash[:event_id] = @event.id
        @events = @current_user.events
        @category_errors = flash[:category_errors]
        @photo = Photo.new
    end
    
    def edit 
    end

    def update 
        @event = Event.find(params[:id])
        @event.update(event_params)
        redirect_to event_path(@event)
    end

    def destroy 
        @event.destroy 
        redirect_to events_path
    end
    
    private

    def set_event
        @event = @current_user.events.find(params[:id])
    end
     
    def event_params
        params.require(:event).permit(:title, :description, :address, :date)
    end  

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    skip_before_action :authorized

    def home 
        if logged_in? 
            redirect_to events_path
        end
    end

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

    def index
    end

    def create 
        Photo.create(picture_url: params[:photo][:picture_url], event_id: flash[:event_id])
        redirect_to event_path(flash[:event_id])
    end

    def destroy 
        photo = Photo.find(params[:id])
        photo.destroy 
        redirect_to event_path(flash[:event_id])
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    skip_before_action :authorized, only: [:login, :handle_login, :new, :create]

  def login
  end

  def handle_login
    @user = User.find_by(username: params[:username])
      if @user && @user.authenticate(params[:password])
        session[:user_id] = @user.id
        redirect_to events_path
      else
        redirect_to login_path
      end
  end

  def logout
    session[:user_id] = nil
    redirect_to root_path
  end

  def new
    @errors = flash[:errors]
    @user = User.new
  end

  def create
    @user = User.create(user_params)
      if @user.valid?
        session[:user_id] = @user.id
        redirect_to events_path
      else
        flash[:errors] = @user.errors.full_messages
        redirect_to new_user_path
      end
  end

  private

  def user_params
    params.require(:user).permit!
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/event_categories_helper.rb
module EventCategoriesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/event_categories/_form.html.erb
<% if @category_errors %>
<% @category_errors.each do |error|%>
    <div class="alert alert-info"><%= error %></div>
  <%end%>
<% end %>

<%= form_for @event_category do |f|%>
<%= f.label :categories %>
<%= f.collection_check_boxes :category_id, @categories, :id, :name%>
<%= f.submit %>
<% end %>

app/views/events/_form.html.erb
<% if @event_errors %>
  <% @event_errors.each do |error|%>
    <div class="alert alert-info"><%= error %></div>
  <%end%>
<% end %>
<div class="container alert alert-success">
  <%= bootstrap_form_for(@event, label_col: "col", control_col: "col-sm-10") do |f| %>
    <div class="form-row">
      <div class="col">
        <%= f.text_field :title %> 
      </div>

      <div class="form-group col-md-6">
        <%= f.text_field :description %>
      </div>

      <div class="form-group col-md-6">
        <%= f.text_field :address %>
      </div>

      <div class="form-group">
        <%= f.datetime_select :date,{start_day: Date.today, start_year: Date.today.year, minute_step: 15, ampm: true} %>
      </div>

      <div class="form-group">
        <%= f.collection_select :category_ids, Category.all, :id, :name %>
      </div>
      
      <div class="form-group">
        <%= f.submit "Add Event", class: "btn btn-primary" %>
      </div>

    </div>
  <%end%>
</div>
<%# bootstrap_form_for(@user, layout: :horizontal, label_col: "col-sm-2", control_col: "col-sm-10") %>

    <%# <%= f.label :title, for: "inlineFormInput" %> 
    <%# <%= f.label :description %>  
    <%# <%= f.label :address%>
    <%# <%= f.label :date, "Date" %>

app/views/events/all_events.html.erb
<h1>All Your Events </h1>
 <div class="list-group">
   <% @all_events.each do |event| %>
      <%= link_to(event, class: "list-group-item list-group-item-action") do  %>  
      <div class="d-flex w-100 justify-content-between">
      <h5 class="mb-1"> <%= event.title %></h5>
      <small class="text-muted"><%= event.days_until_or_since %></small>
      </div>
      <p class="mb-1"><%= event.date.strftime("%A, %B %d") %></p>
      <% end %>
   <%end%>
</div>

app/views/events/edit.html.erb
<div class="container alert alert-success">
  <%= bootstrap_form_for(@event, label_col: "col", control_col: "col-sm-10") do |f| %>
    <div class="form-row">
      <div class="col">
        <%= f.text_field :title %> 
      </div>

      <div class="form-group col-md-6">
        <%= f.text_field :description %>
      </div>

      <div class="form-group col-md-6">
        <%= f.text_field :address %>
      </div>

      <div class="form-group">
        <%= f.datetime_select :date,{start_day: Date.today, start_year: Date.today.year, minute_step: 15, ampm: true} %>
      </div>
      
      <div class="form-group">
        <%= f.submit "Edit Event", class: "btn btn-primary" %>
      </div>

    </div>
  <%end%>
</div>

app/views/events/index.html.erb
<div class="container mt-4">
<h1>Welcome <%=@current_user.first_name%> </h1>

<hr>
  <section class="component">
    
<blockquote class="callout quote EN">
   <%=render "/quotes/quote" %>
  </blockquote>




<h2>Your Upcoming Events </h2>

 <div class="list-group mt-4">
   <% @events.each do |event| %>
      <%= link_to(event, class: "list-group-item list-group-item-action") do  %>  
      <div class="d-flex w-100 justify-content-between">
      <h5 class="mb-1"> <%= event.title.capitalize %></h5>
      <small class="text-muted"><%= event.days_until_or_since %></small>
      </div>
      <p class="mb-1"><%= event.date.strftime("%A, %B %d") %></p>
      <% end %>
   <%end%>
</div>




<div class="row mt-4" > <%= render "form" %> </div>



<h3>Event Filters</h3>

<div class="form-group">
   <%= form_tag(events_path, method: :get) do %> 
      <%= collection_select :event, :category_ids, Category.all, :id, :name %>
      <%# <%= date_select(:search, params[:search]) %> 
      <%= submit_tag("Filter by Category", :id=>"button", :class=>"btn btn-primary", :name=>"submit") %>
   <%end%>
</div>
<div class="form-group">
   <%= form_tag(events_path, method: :get) do%>
      <%= select_year(Date.today, {:prompt => "Year",:start_year => DateTime.now.year,:end_year => DateTime.now.year + 7, prefix: 'select'},{:field_name => 'year', :id => 'start-year', :class => "form-control"}) %>
      <%= select_month(Date.today, {:prompt => "month",use_short_month: true, prefix: 'select', :class => "form-control"},{:field_name => 'month', :id => 'start-month', :class => "form-control"} ) %>
      <%= submit_tag("Filter by Date", :id=>"button", :class=>"btn btn-primary", :name=>"submit") %>
   <%end%>
</div>
</div>

app/views/events/show.html.erb
<div class="card w-75">
  <div class="card-body">

    <h1> <%= @event.title.capitalize %> </h1>

<hr>
<p> <%=@event.date.strftime("%A, %B %d") %> </p>
<p> <%=@event.date.strftime("%I:%M %p") %> </p>
<p> <%=@event.address%> </p>
<p> <%=@event.description%> </p>

<ul> <h6>Categories: </h6>
    <% @event.categories.each do |category| %>
        <li><%= category.name %></li>
    <%end%>
 </ul>



  <p><%= render 'event_categories/form'%></p>
  <p><%= render 'photos/form'%></p>

  <% @event.photos.each do |photo|%>
  <%= image_tag photo.picture_url, width: 200, alt: "event photo" %>
  <%= button_to "X", photo, method: :delete, data: { confirm: 'Are you sure?' } %> 
  <% end %>



 <div class="form-row mt-4">
  <div class="mr-4"><%= link_to "Edit", edit_event_path(@event), class: "btn btn-secondary" %></div>

  <div><%= button_to "Delete Event", @event, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-light" %> </div>
    </div>
  </div>
</div>

<nav aria-label="Page navigation">
<ul class="pagination pagination-sm mt-4">
  <li class="page-item">
  <% if @event.previous.present?%>
  <%= link_to "Previous", @event.previous, class:"page-link"  %></li>
  <% end %>
  <% if @event.next.present? %>
  <li class="page-item"><%= link_to "Next", @event.next, class:"page-link" %>
  <%end%></li>
</ul> 
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>According To Plan</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  </head>

  <body>
 <div class="container">
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo03">  
 
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item">
        <a class="nav-link" href="/events">Calendar<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/all_events">All Events<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/photos">My Photos<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <%= button_to  "Logout", "/logout", method: "delete", class: "btn btn-outline-success my-2 my-sm-0" %>
      </li>
    </ul>
  </div>
</nav>
  


  

    <%= yield %>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pages/home.html.erb
<div class="bg-image p-5 text-center shadow-1-strong rounded mb-5 text-white"
style="background-image: url('https://images.unsplash.com/photo-1611988615248-5d4f0b9ac31e?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1650&q=80');
      height: 100vh">
<div class="container-sm mt-4"><h1>ACCORDING TO PLAN</h1>

<%= link_to 'Create account', new_user_path, class: "btn btn-info" %> 

<%= link_to 'Log in', login_path, class: "btn btn-info" %>
</div>
</div>

app/views/photos/_form.html.erb
<% if @event_errors %>
  <% @event_errors.each do |error|%>
    <div class="alert alert-info"><%= error %></div>
  <%end%>
<% end %>

<%= form_for @photo do |f| %>
<%= f.label :picture_url, "Photo URL" %>
<%= f.text_field :picture_url %>

<%= f.submit "Upload Photo" %>
<%end%>

app/views/photos/index.html.erb
<h1>My Photos:</h1>
<% @current_user.events.each do |event| %>
    <% event.photos.each do |photo| %>
        <%= event.title %><br>
        <%= image_tag photo.picture_url, width: 200, alt: "event photo" %>
    <% end %>
<% end %>

app/views/quotes/_quote.html.erb
<%= @quote %>

app/views/users/login.html.erb
<h1>Login Here</h1>
<div class="container alert alert-success">
<%= form_tag "/handle_login" do %>
  <%= label_tag :username, "Enter Username" %>
  <%= text_field_tag :username %>
  <%= label_tag :password, "Password" %>
  <%= password_field_tag :password %>
  <%= submit_tag "Login", class: "btn btn-primary" %>
<% end %>
</div>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<% if @errors %>
 <% @errors.each do |error|%>
    <div class="alert alert-info"><%= error %></div>
  <%end%>
<% end %>

<div class="container alert alert-success">
  <%= bootstrap_form_for(@user, label_col: "col", control_col: "col-sm-10") do |f| %>
    <div class="form-row">
      <div class="col">
        <%= f.text_field :first_name %> 
      </div>

      <div class="form-group col-md-6">
        <%= f.text_field :last_name %>
      </div>

      <div class="form-group col-md-6">
        <%= f.text_field :username %>
      </div>

      <div class="form-group">
    <%= f.password_field :password %>
      </div>
      
      <div class="form-group">
        <%= f.submit "Sign Up!", class: "btn btn-primary" %>
      </div>

    </div>
  <%end%>
</div>